/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"


void
rand_prog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	long  inicializa_random_1_arg = 5;
	double  *result_2,*r3;
	char *obtiene_siguiente_random_1_arg;
	int i, n=6;

#ifndef	DEBUG
	clnt = clnt_create (host, RAND_PROG, RAND_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	scanf("%ld",&inicializa_random_1_arg);
	printf ("\n");
	scanf("%d",&n);
	result_1 = inicializa_random_1(&inicializa_random_1_arg, clnt);
	//printf ("%f",result_1);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	for (i=0;i<n;i++)
	{
	result_2 = obtiene_siguiente_random_1((void*)&obtiene_siguiente_random_1_arg, clnt);
	printf ("%f\n",*result_2);
	if (result_2 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	int i;
	
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	//for (i=0;i<6;i++)
	//{	
		rand_prog_1 (host);
	//}
exit (0);
}
