/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

float * sum_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->num1+argp->num2;
 	printf("Suma de %f y %f\n",argp->num1,argp->num2);
 	printf("Enviando respuesta: %f\n",result);


	return &result;
}

float *
res_1_svc(inputs *argp, struct svc_req *rqstp){
	static float  result;

	result = argp->num1 - argp->num2;
 	printf("Resta de %f y %f\n",argp->num2,argp->num1);
 	printf("Enviando respuesta : %f\n",result);

	return &result;
}

float *
mul_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->num1 * argp->num2;
 	printf("Multiplicacion de %f y %f\n",argp->num1,argp->num2);
 	printf("Enviando respuesta : %f\n",result);

	return &result;
}

float *
div_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->num1/argp->num2;
	printf("Divicion de %f y %f\n",argp->num1,argp->num2);
	printf("Enviando respuesta: %f\n",result);

	return &result;
}
