/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"


float calculadora_prog_1(char *host,float n1,float n2,char opr,CLIENT *clnt){
//	CLIENT *clnt;
	float  *result_1;
	inputs  sum_1_arg;
	float  *result_2;
	inputs  res_1_arg;
	float  *result_3;
	inputs  mul_1_arg;
	float  *result_4;
	inputs  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


	if(opr=='+'){
 
		 sum_1_arg.num1=n1;
		 sum_1_arg.num2=n2;
		 sum_1_arg.operator=opr;
		  
		 result_1 = sum_1(&sum_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_1;
	}

	else if(opr=='-'){
	 
		 res_1_arg.num1=n1;
		 res_1_arg.num2=n2;
		 res_1_arg.operator=opr;
		  
		 result_2 = res_1(&res_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_2;
	}
	else if(opr=='*'){
 
		 mul_1_arg.num1=n1;
		 mul_1_arg.num2=n2;
		 mul_1_arg.operator=opr;
		  
		 result_3 = mul_1(&mul_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_3;
	}

	else if(opr=='/'){
	 
		 div_1_arg.num1=n1;
		 div_1_arg.num2=n2;
		 div_1_arg.operator=opr;
		  
		 if(n2 == 0){
			 printf("Divicion por cero no es valida.\n");
			 exit(0);
		 }
		else{
		  
			result_4 = div_1(&div_1_arg, clnt);
			if (result_4 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			 return *result_4;
		 }
	}
	
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	float a,b;
	char op;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	printf("Bienvenido a la calculadora por RPC!!!\n");
	 printf("+ Suma\n- Resta\n* Multiplicacion.\n/ Divicion\n");
	 printf("Ingresa numero 1 :\n");
	 scanf("%f",&a);
	 printf("Ingresa numero 2 :\n");
	 scanf("%f",&b);
	 printf("Ingresa la operacion :\n");
	 scanf("%s",&op);

	host = argv[1];
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VER, "udp");

	if (clnt == NULL) {
		 clnt_pcreateerror (host);
		 exit (1);
	 }

	printf("La respuesta es= %f\n",calculadora_prog_1 (host,a,b,op,clnt));
	//calculadora_prog_1 (host);
exit (0);
}
